"""flake-lib artifact hook: resolve a pinned python wheel closure for one declared environment."""

from __future__ import annotations

import hashlib
import importlib.util
import json
import os
import shutil
import subprocess
import tempfile
import tomllib
from pathlib import Path
from typing import Any
from urllib.request import Request, urlopen

from packaging.utils import canonicalize_name, parse_wheel_filename


def load_deps_core():
    spec = importlib.util.spec_from_file_location("deps_core", os.environ["DEPS_CORE"])
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


deps_core = load_deps_core()


def run(*args: str, cwd: Path | None = None) -> None:
    subprocess.run(args, cwd=cwd, check=True)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def checkout_source(work: Path, owner: str, repo: str, revision: str) -> Path:
    source = work / "source"
    run("git", "clone", "--quiet", "--filter=blob:none", "--no-checkout",
        f"https://github.com/{owner}/{repo}.git", str(source))
    run("git", "checkout", "--quiet", revision, cwd=source)
    return source


def source_requirements(source: dict[str, Any], flake_root: Path, checkout: Path | None) -> list[str]:
    kind = source["kind"]
    if kind == "source-pyproject":
        assert checkout is not None
        document = (checkout / "pyproject.toml").read_text()
        requirements = deps_core.pyproject_requirements(document, source.get("groups", []))
        if source.get("buildSystem", False):
            requirements.extend(tomllib.loads(document)["build-system"]["requires"])
        return requirements
    if kind == "source-file":
        assert checkout is not None
        return deps_core.requirements_file_requirements((checkout / source["path"]).read_text())
    if kind == "repo-file":
        return deps_core.requirements_file_requirements((flake_root / source["path"]).read_text())
    raise ValueError(f"unknown wheelhouse source kind: {kind}")


def wheel_url(index_url: str, name: str, filename: str, digest: str) -> str:
    request = Request(
        f"{index_url.rstrip('/')}/{canonicalize_name(name)}/",
        headers={"Accept": "application/vnd.pypi.simple.v1+json"},
    )
    with urlopen(request) as response:
        files = json.load(response)["files"]
    for item in files:
        if item["filename"] == filename and item.get("hashes", {}).get("sha256") == digest:
            return item["url"]
    raise RuntimeError(f"the index did not report {filename} with {digest}")


def main() -> None:
    flake_root = Path(os.environ["FLAKE_ROOT"])
    revision = os.environ["NEW_REV"]
    spec = json.loads(os.environ["WHEELHOUSE_SPEC"])
    index_url = os.environ["INDEX_URL"]
    owner = os.environ["GH_OWNER"]
    repo = os.environ["GH_REPO"]

    needs_checkout = any(source["kind"] != "repo-file" for source in spec["sources"])

    with tempfile.TemporaryDirectory(prefix="python-wheelhouse-") as raw_work:
        work = Path(raw_work)
        checkout = checkout_source(work, owner, repo, revision) if needs_checkout else None

        requirements = []
        for source in spec["sources"]:
            requirements.extend(source_requirements(source, flake_root, checkout))
        requirements.extend(spec.get("extraRequirements", []))
        deduplicated = list(dict.fromkeys(requirements))
        if not deduplicated:
            raise RuntimeError("the wheelhouse spec produced no requirements")

        header = "# Generated by flake-lib python-wheelhouse"
        if needs_checkout:
            header += f" from {owner}/{repo}@{revision}"
        requirements_in = work / "requirements.in"
        requirements_in.write_text(f"{header}\n" + "\n".join(deduplicated) + "\n")

        requirements_lock = work / "requirements.lock"
        run(
            "uv", "pip", "compile", requirements_in.name,
            "--python-version", spec["uvPythonVersion"],
            "--python-platform", spec["uvPythonPlatform"],
            "--generate-hashes",
            "--index-url", index_url,
            "--output-file", requirements_lock.name,
            "--no-header",
            cwd=work,
        )

        wheelhouse = work / "wheelhouse"
        wheelhouse.mkdir()
        run(
            "pip", "download",
            "--require-hashes",
            "--only-binary", ":all:",
            "--dest", str(wheelhouse),
            "--platform", spec["pipPlatform"],
            "--python-version", spec["pipPythonVersion"],
            "--implementation", "cp",
            "--abi", spec["pipAbi"],
            "--index-url", index_url,
            "--requirement", str(requirements_lock),
        )

        manifest = []
        for artifact in sorted(wheelhouse.glob("*.whl"), key=lambda path: path.name.lower()):
            name, version, _build, _tags = parse_wheel_filename(artifact.name)
            digest = sha256(artifact)
            manifest.append({
                "name": canonicalize_name(name),
                "version": str(version),
                "filename": artifact.name,
                "url": wheel_url(index_url, str(name), artifact.name, digest),
                "sha256": digest,
                "size": artifact.stat().st_size,
            })
        if not manifest:
            raise RuntimeError("pip download produced no wheels")

        wheel_manifest = work / "wheels.json"
        wheel_manifest.write_text(json.dumps(manifest, indent=2) + "\n")

        shutil.copy2(requirements_in, flake_root / "requirements.in")
        shutil.copy2(requirements_lock, flake_root / "requirements.lock")
        shutil.copy2(wheel_manifest, flake_root / "wheels.json")

        print(f"requirementsHash={sha256(requirements_lock)}")
        print(f"wheelManifestHash={sha256(wheel_manifest)}")


if __name__ == "__main__":
    main()
